name: flutter_eng_cycle_times
publish-to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.3
dependencies: 
  dio: ^4.0.0
  github: ^8.1.0
  http: ^0.13.3
  dio_cache_interceptor: ^2.3.1
